<%@ page import="java.sql.*" %>


<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<html>
<body>
<%


    String isimm = request.getParameter("isim");
    String soyisimm = request.getParameter("soyisim");
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/tez",
            "root", "root");
    
    PreparedStatement Statement = conn
            .prepareStatement("select * from kullanici where isim='"+isimm+"' and soyisim='"+soyisimm+"'");
    
   ResultSet result= Statement.executeQuery();
    if (result.next()) {

            System.out.println("mevcut kullanici");
            response.sendRedirect(request.getContextPath()+"/home");
        }else{
    PreparedStatement Statement2 = conn
            .prepareStatement("INSERT INTO kullanici (isim, soyisim) " +
                    "VALUES (?,?)", PreparedStatement.RETURN_GENERATED_KEYS);

    Statement2.setString(1, isimm);
    Statement2.setString(2, soyisimm);
        session.setAttribute("isim", isimm);
        session.setAttribute("soyisim", soyisimm);


    Statement2.executeUpdate();

    ResultSet tableKeys = Statement2.getGeneratedKeys();
    tableKeys.next();
    int autoGeneratedID = tableKeys.getInt(1);
    
    request.getSession(true).setAttribute("Id", autoGeneratedID);
    
    //response.sendRedirect(request.getContextPath()+"/websearch?q="+request.getSession().getAttribute("Id"));
        response.sendRedirect(request.getContextPath() + "/search_form");
    }
    
%>

</body>
</html>